spring:
  security:
    user:
      name: test
      password: test1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://49.50.165.98:3306/boot_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: boot
    password: Team2@boot(^
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        shutdownTimeout: 30000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update #update create
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: DEBUG
    org.springframework: DEBUG
jwt:
  header: Authorization
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
  #token-validity-in-seconds: 86400
  token-validity: 3600000  # 1시간 (밀리초 단위)

file:
  path: /var/upload/

endpoint:
  path: /payment/api
